Class Busrecpacpatvida.Message.Klap.Request.GetCalendario Extends (%Persistent, %XML.Adaptor)
{

Property fecha As %String;

Storage Default
{
<Data name="GetCalendarioDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>fecha</Value>
</Value>
</Data>
<DataLocation>^Busrecpacpat8E1D.GetCalendarioD</DataLocation>
<DefaultData>GetCalendarioDefaultData</DefaultData>
<IdLocation>^Busrecpacpat8E1D.GetCalendarioD</IdLocation>
<IndexLocation>^Busrecpacpat8E1D.GetCalendarioI</IndexLocation>
<StreamLocation>^Busrecpacpat8E1D.GetCalendarioS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

