Class Busrecpacpatvida.Message.RespuestaKlap.Response.RespuestaKlapResponse Extends (%Persistent, %XML.Adaptor)
{

Property fecha As %String;

Storage Default
{
<Data name="RespuestaKlapResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>fecha</Value>
</Value>
</Data>
<DataLocation>^Busrecpacp4C01.RespuestaKl6A57D</DataLocation>
<DefaultData>RespuestaKlapResponseDefaultData</DefaultData>
<IdLocation>^Busrecpacp4C01.RespuestaKl6A57D</IdLocation>
<IndexLocation>^Busrecpacp4C01.RespuestaKl6A57I</IndexLocation>
<StreamLocation>^Busrecpacp4C01.RespuestaKl6A57S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

