Class Busrecpacpatvida.Message.TerminoRecaudacion.Request.TerminoRecaudacionRequest Extends (%Persistent, %XML.Adaptor)
{

Storage Default
{
<Data name="TerminoRecaudacionRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Busrecpacp667F.TerminoRecaAC2BD</DataLocation>
<DefaultData>TerminoRecaudacionRequestDefaultData</DefaultData>
<IdLocation>^Busrecpacp667F.TerminoRecaAC2BD</IdLocation>
<IndexLocation>^Busrecpacp667F.TerminoRecaAC2BI</IndexLocation>
<StreamLocation>^Busrecpacp667F.TerminoRecaAC2BS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

