Class Busrecpacpatvida.Message.TerminoRecaudacion.Response.TerminoRecaudacionResponse Extends (%Persistent, %XML.Adaptor)
{

Property resultadoTermino As %String;

Storage Default
{
<Data name="TerminoRecaudacionResponseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>resultadoTermino</Value>
</Value>
</Data>
<DataLocation>^BusrecpacpC7BB.TerminoReca3870D</DataLocation>
<DefaultData>TerminoRecaudacionResponseDefaultData</DefaultData>
<IdLocation>^BusrecpacpC7BB.TerminoReca3870D</IdLocation>
<IndexLocation>^BusrecpacpC7BB.TerminoReca3870I</IndexLocation>
<StreamLocation>^BusrecpacpC7BB.TerminoReca3870S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}

